version: '3.7'
services:
  postgres_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=pgroot
    volumes:
      - ./postgre-db:/data/db
    ports:
      - 5432:5432
